<a href="https://colab.research.google.com/github/abaninarendra/Algorithms/blob/master/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference: Python for Data Analysis _ WesMcKinney
## Chapter 2 - Numpy

**Simple random data**: generates array of random numbers from uniform or normal distributions or random integers within a specified range. <br>
 | Function         | Description                                                                 |
|-----------------|-----------------------------------------------------------------------------|
| `arange()`       | A range of evenly spaced numbers — similar to Python’s `range()`, but returns a NumPy array. |
| `rand()`         | Generates random floats between 0 and 1 (uniform distribution).            |
| `randn()`        | Generates random numbers from standard normal distribution (mean=0, std=1). |
| `randint()`      | Generates random integers from a specified range.                          |
| `random_sample()`| Generates random floats in [0.0, 1.0).                                     |

**Permutations**: randomly reorder elements of an array or return a random permutation of a range. <br>
	- shuffle() <br>
	- permutation() <br>
**Distributions** - sample from wide variety of probability distributions
	- `normal()`: Normal (Gaussian) distribution<br>
    - `uniform()`: Uniform distribution<br>
    - `poisson()`: Poisson distribution<br>
    - `binomial()`: Binomial distribution<br>
    - `exponential()`: Exponential distribution<br>
 **Random generator**:
	 `default_rng()` function provides a modern and recommended way to create a `Generator` object, which encapsulates the state of the random number generation process. This allows for better control over reproducibility and parallelism.

# .arange
syntax:
.arange(start,stop,step, dtype=)

# NumPy dtypes: Example & Memory Size

| Dtype          | Example Output                                | Memory Size (of one element explained next) |
|----------------|-----------------------------------------------|------------------|
| np.int8        | [0 1 2 3 4]                                  | 1                |
| np.int16       | [0 1 2 3 4]                                  | 2                |
| np.int32       | [0 1 2 3 4]                                  | 4                |
| np.int64       | [0 1 2 3 4]                                  | 8                |
| float          | [0. 0.5 1. 1.5 2. 2.5 3. 3.5 4. 4.5]        | 8                |
| np.float16     | [0. 0.5 1. 1.5 2. 2.5 3. 3.5 4. 4.5]        | 2                |
| np.float32     | [0. 0.5 1. 1.5 2. 2.5 3. 3.5 4. 4.5]        | 4                |
| np.float64     | [0. 0.5 1. 1.5 2. 2.5 3. 3.5 4. 4.5]        | 8                |
| np.complex64   | [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]        | 8                |
| np.complex128  | [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]        | 16               |


In [15]:
import numpy as np
#np.arange(start,stop,step,dtype=None)
a=np.arange(0,10,2,dtype=None) # Changed dtype to str
print(a)

a_float=np.arange(0,5,dtype=float)
print(a_float)

#check memory size

arr1_int8=np.array([1],dtype=np.int8)
arr2_int8=np.array([1,2,3,4],dtype=np.int8)

print("int8 arr1 itemsize:",arr1_int8.itemsize,"nbytes:",arr1_int8.nbytes)
print("int8 arr2 itemsize:",arr2_int8.itemsize,"nbytes:",arr2_int8.nbytes)

arr1_int16=np.array([1],dtype=np.int16)
arr2_int16=np.array([1,2,3,4],dtype=np.int16)

print("int16 arr1 itemsize:",arr1_int16.itemsize,"nbytes:",arr1_int16.nbytes)
print("int16 arr2 itemsize:",arr2_int16.itemsize,"nbytes:",arr2_int16.nbytes)

arr1_int32=np.array([1],dtype=np.int32)
arr2_int32=np.array([1,2,3,4],dtype=np.int32)

print("int32 arr1 itemsize:",arr1_int32.itemsize,"nbytes:",arr1_int32.nbytes)
print("int32 arr2 itemsize:",arr2_int32.itemsize,"nbytes:",arr2_int32.nbytes)



[0 2 4 6 8]
[0. 1. 2. 3. 4.]
int8 arr1 itemsize: 1 nbytes: 1
int8 arr2 itemsize: 1 nbytes: 4
int16 arr1 itemsize: 2 nbytes: 2
int16 arr2 itemsize: 2 nbytes: 8
int32 arr1 itemsize: 4 nbytes: 4
int32 arr2 itemsize: 4 nbytes: 16


In [4]:
import numpy as np

data={i:np.random.randn() for i in range(7)}
print(data)

{0: -0.4125554454978472, 1: -0.043460386429820835, 2: -1.8068641505561727, 3: -0.1998527277488442, 4: 2.8298715589835615, 5: 0.040237531281267544, 6: -0.4336852140091657}


#np.random.rand()
Generates random floats between 0 and 1 (uniform distribution).

In [21]:
import numpy as np
a=np.random.rand(5)
print(a)

two_d_array=np.random.rand(5,2)
print(two_d_array
    )

[0.90157075 0.93997027 0.570648   0.42534075 0.56862699]
[[0.4526859  0.6160608 ]
 [0.2802643  0.2040145 ]
 [0.98297136 0.68331039]
 [0.1696442  0.38553261]
 [0.57776786 0.43466572]]


#np.random.randn()
Generates random numbers from standard normal distribution (mean=0, std=1).


In [19]:
import numpy as np
a=np.random.randn(3,3)
print(a)
two_d_array = np.random.randn(2, 3)

print(two_d_array)

[[ 0.47358076 -0.34168577 -2.63637049]
 [ 0.4514057   0.72069747 -0.94040709]
 [ 1.45642683 -1.15674426 -0.89509399]]


In [23]:
import numpy as np

# Generate a 2x3 array of random numbers from the standard normal distribution
two_d_array = np.random.randn(2, 3)

print(two_d_array)

[[-1.32446523  0.62781124  0.96181182]
 [ 2.37765986  1.22063857 -1.6465844 ]]


#numpy.random.randint()
Generates random integers from a specified range.


In [34]:
import numpy as np
# Generate a 2D array of random integers between 0 (inclusive) and 10 (exclusive)
print(np.random.randint(0, 10, size=(4, 3,20))) # 4 arrays of 3 rows x 20 columns

[[[7 5 6 4 0 5 9 1 3 0 3 2 2 6 3 3 3 5 2 4]
  [4 9 1 1 9 9 2 0 0 6 8 2 9 8 1 4 2 1 5 3]
  [4 4 0 8 6 7 5 8 2 6 3 7 9 8 3 4 7 0 4 2]]

 [[3 7 1 5 9 9 3 1 1 6 1 9 8 4 9 2 8 7 9 1]
  [7 2 1 4 3 6 0 7 7 1 9 5 5 9 7 3 7 7 7 9]
  [7 2 8 6 9 1 1 3 4 3 1 5 0 1 5 3 7 0 5 2]]

 [[7 3 0 0 4 7 7 7 7 6 9 9 6 0 3 6 1 4 9 1]
  [2 8 8 4 0 4 0 2 1 5 4 9 0 2 6 0 8 3 0 9]
  [2 2 5 4 6 0 1 0 4 1 8 7 2 8 4 8 1 2 7 6]]

 [[0 4 2 2 5 4 8 0 4 3 9 5 4 4 2 2 4 0 6 7]
  [5 1 4 6 5 4 2 9 6 7 7 1 3 7 6 8 6 2 6 1]
  [2 8 0 7 1 8 4 0 0 8 2 5 4 8 8 0 8 6 6 3]]]


#numpy.random.random_sample()
Takes only one argument <br>
Generates random floats in the range [0.0, 1.0).

In [36]:
import numpy as np
# Generate an array of 10 random floats between 0.0 and 1.0
print(np.random.random_sample(10)) # Corrected by providing a size argument

[0.61167727 0.56784659 0.88061464 0.19111035 0.7544131  0.71669636
 0.09066823 0.58688631 0.88356515 0.60343574]
